// Educational simulation ranges, not calibrated soil sensor measurements.
// Botanical references and the limits of this model: docs/plant-model.md.
export const SPECIES_CARE = {
  tomato: { name: 'Solanum lycopersicum', moisture: [45, 70], temp: [20, 29], pace: 1,
    sow: 'Ươm hạt trong giá thể thoáng; chuyển cây con sang chậu có lỗ thoát nước.',
    support: 'Cắm cọc đỡ thân từ giai đoạn cây con. Tưới quanh gốc, giữ ẩm đều.',
    flowering: 'Hoa vàng nhỏ mọc thành chùm. Rung nhẹ chùm hoa hỗ trợ tự thụ phấn.',
    fruiting: 'Quả xanh lớn dần rồi chuyển đỏ. Tránh để đất khô rồi tưới quá nhiều.',
    mature: 'Hái quả đã lên màu đều; giữ lại cành và lá khỏe.' },
  pepper: { name: 'Capsicum annuum', moisture: [40, 65], temp: [22, 30], pace: 1.15,
    sow: 'Ươm ở nơi ấm, giá thể ẩm vừa. Cây con cần được làm quen dần với nắng.',
    support: 'Thân phân nhánh; giữ gốc thoáng và tránh nước đọng trong chậu.',
    flowering: 'Hoa nhỏ màu trắng ở nách lá, có khả năng tự thụ phấn.',
    fruiting: 'Quả thuôn dài từ xanh chuyển đỏ; tăng trưởng chậm hơn cà chua trong mô phỏng.',
    mature: 'Cắt cuống quả bằng dụng cụ sạch, tránh kéo gãy cành.' },
  bean: { name: 'Phaseolus vulgaris · dạng leo', moisture: [45, 70], temp: [20, 28], pace: .8,
    sow: 'Gieo trực tiếp vào đất thoát nước tốt. Mô hình này là đậu leo, không đại diện mọi giống đậu.',
    support: 'Dựng giàn sớm để thân quấn quanh cọc. Lá trưởng thành gồm ba lá chét.',
    flowering: 'Hoa nhỏ ở nách lá. Đậu thường tự thụ phấn; hỗ trợ là tùy chọn.',
    fruiting: 'Quả đậu dài buông xuống, hạt lớn dần trong vỏ quả.',
    mature: 'Thu quả còn non để ăn tươi; không chờ vỏ khô nếu muốn đậu giòn.' },
  carrot: { name: 'Daucus carota', moisture: [45, 65], temp: [16, 24], pace: 1,
    sow: 'Gieo trực tiếp trong đất tơi sâu, ít sỏi; tránh chuyển cây làm tổn thương rễ chính.',
    support: 'Tỉa bớt cây mọc sát nhau. Lá xẻ nhỏ phía trên, rễ phình thành củ bên dưới đất.',
    flowering: 'Củ đang lớn dưới đất. Cà rốt lấy củ không cần qua giai đoạn hoa hay thụ phấn.',
    fruiting: 'Theo dõi phần vai củ; không xới sát rễ hoặc bón quá nhiều đạm.',
    mature: 'Làm ẩm đất rồi nhổ củ nhẹ nhàng. Hình cắt lớp chỉ để quan sát rễ.' },
  corn: { name: 'Zea mays', moisture: [50, 75], temp: [20, 30], pace: 1.1,
    sow: 'Gieo trực tiếp; ngoài thực tế nên trồng thành cụm nhiều hàng để hỗ trợ thụ phấn nhờ gió.',
    support: 'Thân thẳng có đốt, lá dài ôm thân. Bắp cần không gian và đất đủ sâu.',
    flowering: 'Cờ đực ở ngọn phát tán phấn; râu bắp ở nách lá nhận phấn.',
    fruiting: 'Hạt phát triển trong bẹ bắp. Giữ ẩm đều trong thời kỳ ra râu và nuôi hạt.',
    mature: 'Râu bắp chuyển nâu, hạt căng. Không nhầm cờ ở ngọn với bắp thu hoạch.' },
  sunflower: { name: 'Helianthus annuus', moisture: [40, 65], temp: [20, 29], pace: 1,
    sow: 'Gieo nơi nhiều nắng, đất thoát nước. Chọn giống lùn nếu trồng chậu.',
    support: 'Thân đứng, lá rộng có răng cưa; giống cao cần cọc đỡ khi có gió.',
    flowering: 'Cụm hoa có cánh vàng bao quanh đĩa hoa giữa; côn trùng hỗ trợ thụ phấn.',
    fruiting: 'Cánh hoa tàn dần, đầu hoa nặng và cúi xuống khi hạt hình thành.',
    mature: 'Chờ mặt sau đầu hoa ngả vàng nâu và hạt đầy trước khi thu.' },
  herb: { name: 'Ocimum basilicum · mô hình húng quế', moisture: [45, 70], temp: [20, 29], pace: .7,
    sow: 'Rau thơm có nhiều loài; mô phỏng này dùng húng quế với các cặp lá mọc đối.',
    support: 'Bấm ngọn phía trên một cặp lá để cây phân nhánh; chừa lá khỏe để cây tiếp tục lớn.',
    flowering: 'Nuôi tán lá thay vì chờ hoa. Ngắt nụ để ưu tiên thu hoạch lá.',
    fruiting: 'Hái lá và ngọn non, không có quả để thu trong chu kỳ này.',
    mature: 'Thu một phần ngọn, giữ lại các đốt lá. Không cắt trụi cả cây.' },
};
