/**
 * Self-hosts the two typefaces rather than linking Google's stylesheet.
 *
 * A stylesheet from fonts.googleapis.com is a render-blocking request to a
 * third party on every page load, and the one thing on this site that stops
 * working if that host is slow or blocked. The files are small enough to ship.
 *
 * Only the latin, latin-ext and vietnamese subsets are kept. Baloo 2 also
 * ships devanagari, which is a third of its weight and no use here.
 *
 * Re-run with: npm run fonts
 */
const fs = require('fs');
const path = require('path');

/** The exact families and weights the site asks for. */
const SPEC =
  'family=Be+Vietnam+Pro:wght@400;500;600;700;800&family=Baloo+2:wght@500..800&display=swap';

// Google serves woff2 only to a user agent it recognises as supporting it.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = 'public/assets/fonts';
const OUT_CSS = 'src/styles/fonts.css';
const KEEP = ['latin', 'latin-ext', 'vietnamese'];

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

async function main() {
  const sheet = await fetch(`https://fonts.googleapis.com/css2?${SPEC}`, {
    headers: { 'User-Agent': UA },
  });
  if (!sheet.ok) throw new Error(`google fonts -> ${sheet.status}`);
  const css = await sheet.text();

  // Google writes a /* subset */ comment above each face.
  const blocks = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) blocks.push({ subset: m[1], body: m[2] });
  if (!blocks.length) throw new Error('no @font-face blocks found');

  fs.mkdirSync(OUT_DIR, { recursive: true });

  const faces = [];
  for (const { subset, body } of blocks) {
    if (!KEEP.includes(subset)) continue;

    const family = /font-family:\s*'([^']+)'/.exec(body)[1];
    const weight = /font-weight:\s*([^;]+);/.exec(body)[1].trim();
    const range = /unicode-range:\s*([^;]+);/.exec(body)[1].trim();
    const url = /url\((https:[^)]+\.woff2)\)/.exec(body)[1];

    const file = `${slug(family)}-${weight.replace(/\s+/g, '-')}-${subset}.woff2`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url} -> ${res.status}`);
    fs.writeFileSync(path.join(OUT_DIR, file), Buffer.from(await res.arrayBuffer()));

    faces.push(
      '@font-face {',
      `  font-family: '${family}';`,
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('/assets/fonts/${file}') format('woff2');`,
      `  unicode-range: ${range};`,
      '}',
      '',
    );
  }

  const header = [
    '/* Be Vietnam Pro and Baloo 2, self-hosted.',
    '',
    '   The typefaces these replace were not missing Vietnamese glyphs: every',
    '   one is in the cmap with real outlines. They were drawn without stacked',
    '   diacritics in mind, so the tone mark on ế, ộ, ữ, ẩ lands on top of the',
    '   circumflex rather than beside it, and at UI sizes the two run together.',
    '',
    '   Both of these had Vietnamese in the brief: Be Vietnam Pro from a',
    '   Vietnamese foundry, and Baloo 2 is the rewrite of Baloo that fixed its',
    '   Vietnamese.',
    '',
    '   Generated by scripts/fetch-fonts.cjs. Do not edit by hand. */',
    '',
  ];

  fs.writeFileSync(OUT_CSS, header.concat(faces).join('\n'));
  console.log(`Da tai ${faces.length / 9} file woff2 vao ${OUT_DIR}`);
  console.log(`Da ghi ${OUT_CSS}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
